//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        public int LotID { get; set; }
        public string LotName { get; set; }
        public string LatLong { get; set; }
        public string Website { get; set; }
        public Nullable<int> NumOfSpaces { get; set; }
        public Nullable<int> NumOfOccupants { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> OwnerID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
